name: findeals
description: "A smart offer aggregator based on financial products"
publish_to: 'none'  # Keep this line to prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.6.1  # Keep the same SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.0
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.70.2
  excel: ^2.1.0
  path_provider: ^2.1.0
  sqflite: ^2.4.2
  supabase_flutter: ^2.8.4
  workmanager: ^0.6.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.4.0
  string_similarity: ^2.0.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.1
  get: ^4.6.6
  intl_phone_field: ^3.2.0
  webview_flutter: ^4.13.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"  # Make sure this is the correct path

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png 
    - assets/logos/ # Ensures Flutter recognizes the icon file
    - .env
    - assets/data/
