# name: flutter_application_1
# description: "A new Flutter project."
# publish_to: 'none' 

# version: 1.0.0+1

# environment:
#   sdk: ^3.7.0

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.8

#   #  Add intl_phone_field for country code selection in phone input
#   intl_phone_field: ^3.1.0
#   firebase_core: ^3.12.1
#   firebase_auth: ^5.5.1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true



name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.1.0  
  firebase_core: ^3.12.1  
  firebase_auth: ^5.5.1   
  shared_preferences: ^2.5.3
  permission_handler: ^11.0.1  
  telephony: ^0.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
